// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyShoppy.DataAccess.Data;

#nullable disable

namespace MyShoppy.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyShoppy.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2024, 7, 16, 20, 57, 37, 167, DateTimeKind.Local).AddTicks(6894),
                            Description = "",
                            Name = "Phones"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2024, 7, 17, 20, 57, 37, 167, DateTimeKind.Local).AddTicks(6903),
                            Description = "",
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2024, 7, 18, 20, 57, 37, 167, DateTimeKind.Local).AddTicks(6908),
                            Description = "",
                            Name = "Electronics"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
